# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCadastrodeusurio():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cadastrodeusurio(self):
    self.driver.get("https://www.cacaushow.com.br/")
    self.driver.set_window_size(1552, 832)
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, "ul:nth-child(2) > li:nth-child(2) .it__above--text").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "cadastro").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lovers-input__container:nth-child(4) > #cpf").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lovers-input__container:nth-child(4) > #cpf").send_keys("727.478.900-74")
    self.driver.find_element(By.CSS_SELECTOR, ".form__continuar > #continuar").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "nome").send_keys("Teste")
    self.driver.find_element(By.ID, "sobrenome").click()
    self.driver.find_element(By.ID, "sobrenome").send_keys("Qualidade")
    self.driver.find_element(By.CSS_SELECTOR, ".form__continuar > #continuar").click()
    self.driver.find_element(By.ID, "dataNascimento").click()
    self.driver.find_element(By.ID, "dataNascimento").send_keys("12/09/1984")
    self.driver.find_element(By.CSS_SELECTOR, ".form__continuar > #continuar").click()
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.ID, "login").send_keys("teste@teste2.qualidade.com")
    self.driver.find_element(By.ID, "celular").click()
    self.driver.find_element(By.ID, "celular").send_keys("(11) 99991-2789")
    self.driver.find_element(By.CSS_SELECTOR, ".form__continuar > #continuar").click()
    self.driver.find_element(By.ID, "senha").click()
    self.driver.find_element(By.ID, "senha").send_keys("Teste12345")
    self.driver.find_element(By.CSS_SELECTOR, ".form__continuar > #continuar").click()
    self.driver.find_element(By.ID, "confirmarSenha").click()
    self.driver.find_element(By.ID, "confirmarSenha").send_keys("Teste12345")
    self.driver.find_element(By.ID, "termos").click()
    self.driver.find_element(By.ID, "cadastrar").click()
    element = self.driver.find_element(By.ID, "cadastrar")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".visibility > .popup > .popup__fechar > .fechar").click()
    
  
 