# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBotaodeacessibilidadeLibras():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_botaodeacessibilidadeLibras(self):
    self.driver.get("https://www.cacaushow.com.br/")
    self.driver.set_window_size(913, 673)
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-rybena-sign-language > .ryb-ignore:nth-child(1)").click()
    element = self.driver.find_element(By.ID, "rybena-handle-top")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "rybena-handle-top")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "rybena-handle-top")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "rybena-handle-top").click()
    self.driver.find_element(By.CSS_SELECTOR, ".content-asset:nth-child(2)").click()
    self.driver.switch_to.frame(11)
    self.driver.switch_to.default_content()
    element = self.driver.find_element(By.ID, "editable-text-1541975415318")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#editable-text-1541975415318 > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#editable-text-1541975415305 > div:nth-child(3) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#editable-text-1541975415343 > span:nth-child(1)").click()
  
