# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCompradeproduto():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_compradeproduto(self):
    self.driver.get("https://www.cacaushow.com.br/")
    self.driver.set_window_size(1552, 832)
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "image-1541975415305").click()
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".it__minicart .minicart-link > .minicart-quantity").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkout-btn").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//div/input").send_keys("teste@teste2.qualidade.com")
    self.driver.find_element(By.ID, "login-btn-toggle").click()
    self.driver.find_element(By.ID, "login-form-password").click()
    self.driver.find_element(By.ID, "login-form-password").send_keys("Teste12345")
    self.driver.find_element(By.ID, "login-btn-toggle").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".js-nextStep1:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pix-tab").click()
    self.driver.find_element(By.CSS_SELECTOR, ".next-summary").click()
    self.driver.execute_script("window.scrollTo(0,0)")
  
